### ISSUE TITLE
Add CDN support

### ISSUE THREAD

**Issue by joseluisq** [IonicaBizau/gridly#1]
It will be great you may considerate to add your production file to some CDN server.
Great job!

**Comment by IonicaBizau** [comment]
@joseluisq Of course! It will probably be available on cdnjs.com (@cdnjs) if it gets more popular. :dizzy:  

Thanks! :joy:

**Comment by joseluisq** [comment]
@IonicaBizau fantastic ! :+1:

**Comment by IonicaBizau** [comment]
@joseluisq In the meantime, you can use `cdn.rawgit.com`:

```
https://cdn.rawgit.com/IonicaBizau/gridly/gh-pages/dist/gridly.min.css
```

**Comment by joseluisq** [comment]
Cool :+1: 
Thanks !

**Comment by PeterDaveHello** [comment]
@IonicaBizau do you not use your importer to import it :smile:

**Comment by IonicaBizau** [comment]
@PeterDaveHello :joy:

**Comment by joseluisq** [comment]
https://github.com/IonicaBizau/gridly#rocket-available-on-cdn :+1:
