### ISSUE TITLE
col-half + (col-quarter * 2) != 1

### ISSUE THREAD

**Issue by burakcan** [IonicaBizau/gridly#10]
![screen shot 2015-12-16 at 11 28 37](https://cloud.githubusercontent.com/assets/3121257/11837245/4c7bf560-a3e8-11e5-91d6-6417111eb10b.png)

**Comment by IonicaBizau** [comment]
I guess it's because of the paddings/margins I added. :joy:

**Comment by IonicaBizau** [comment]
This only affects the example. :smile:

**Comment by lcristianiim** [comment]
Tried to reproduce `col-half + (col-quarter * 2) != 1` but in my example works as expected:
[here](https://jsfiddle.net/lcristianiim/emhqyay2/). @burakcan  can you provide similar example like mine?

**Comment by burakcan** [comment]
i only tried on the demo page :) so, it looks like its working as expected

**Comment by IonicaBizau** [comment]
@burakcan Yes, this happens because of the margins and paddings I added in the example page. I'm sure there is a way to set the padding/margin without modifying the width. :dizzy:

**Comment by burakcan** [comment]
For paddings, `box-sizing: border-box` does the job but i'm not sure about margins.
But; using col's as wrappers and setting col gaps inside them (no spacing between cols) should be fine.

```
<div class='col'>
   <div class='content-with-spacing' />
</div>
<div class='col'>
   <div class='content-with-spacing' />
</div>
<div class='col'>
   <div class='content-with-spacing' />
</div>
```

**Comment by IonicaBizau** [comment]
@burakcan Would be nice if you changed that in the example. I struggled a lot doing that, honestly. :smile: 

Basically, I would like to have the same design (visible margins between columns), but also handle the case you specified or `4 * .col-quarter === 1` and so on.

PRs are welcome in that direction! :grin:

**Comment by burakcan** [comment]
@IonicaBizau here: https://github.com/IonicaBizau/gridly/pull/11 :)
