### ISSUE TITLE
Add support for IE11 and prefixed settings

### ISSUE THREAD

**Issue by gmariani** [IonicaBizau/gridly#20]
While I love the concept of Gridly, using this on client sites has been getting me hollered at for small bugs with IE11. I get we can't support every version of IE, but IE11 touts it supports flexbox. Poorly though.

From my experience I've learned that it doesn't use the default settings of 'flex:1' like the rest of the browsers. So you must be more explicit for it to work properly. Also adding the prefixed versions of the props can't hurt. I did read your 'guidelines' for contributing, but seemed like overkill for a project which literally has two lines of (compressed) CSS.

```
.row{display:-ms-flexbox;display:-webkit-flex;display:flex;}
.col{-ms-flex-grow:1;-webkit-flex-grow:1;flex-grow:1}

@media(max-width:48em){
.row{-ms-flex-direction: column;-webkit-flex-direction: column;flex-direction:column;}
.col{flex:0 0 auto}
}
```

**Comment by IonicaBizau** [comment]
> I did read your 'guidelines' for contributing, but seemed like overkill for a project which literally has two lines of (compressed) CSS.

:grin: That file is generated. [Here](https://ionicabizau.net/blog/33-how-i-npm) I described the process how I create packages.

**Comment by IonicaBizau** [comment]
Isn't autoprefixer supposed to add the `-ms` prefixes too? :thought_balloon: /cc @phoenixenero #13 

The [`prefixed` ](https://github.com/IonicaBizau/gridly/tree/gh-pages/dist/prefixed) directory contains the prefixed CSS.

Thanks a lot for heads-up!

**Comment by tunnckoCore** [comment]
@IonicaBizau it can be because IE11 don't have more than 5% usage? (that's in postcssjson).

**Comment by IonicaBizau** [comment]
Good point. Hmm, maybe should we remove that option? 💥

**Comment by tunnckoCore** [comment]
Mm nope. If i remember correctly, by defaults it uses 1%. So i think it will work if increase it.

**Comment by gmariani** [comment]
Looking at browser usage IE11 hovers above 5% to 17%
https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0
https://www.w3counter.com/globalstats.php

I also apologize i didn't even notice the prefixed folder, i just bookmarked the main one and haven't looked back.

Also for the flex:1 bug, this lists a good bit of the flexbox bugs: https://github.com/philipwalton/flexbugs

Excerpt:

> Prior to the release of IE 10, the flexbox spec at the time stated that a flexbox item's preferred size required a unit when using the flex shorthand:
> 
> If the 'preferred-size' is ‘0’, it must be specified with a unit (like ‘0px’) to avoid ambiguity; unitless zero will either be interpreted as as one of the flexibilities, or is a syntax error.
> 
> This is no longer true in the spec, but IE 10-11 still treat it as true. If you use the declaration flex: 1 0 0 in one of these browsers, it will be an error and the entire rule (including all the flexibility properties) will be ignored.
> Workaround
> 
> When using the flex shorthand, always include a unit in the flex-basis portion. For example: 1 0 0%.
> 
> Important: using a flex value of something like 1 0 0px can still be a problem because many CSS minifiers will convert 0px to 0. To avoid this, make sure to use 0% instead of 0px since most minifiers won't touch percentage values for other reasons.

**Comment by IonicaBizau** [comment]
@gmariani I'm using Gridly in a new project that should (probably) be compatible with IE. On IE11 I don't see any issues. Can you create a demo and show how it's failing?

Thanks!

**Comment by IonicaBizau** [comment]
Seems to work fine on IE11.

**Comment by gmariani** [comment]
I"m very sorry for not responding sooner. I saw you just now closed the ticket but here is an example of the IE11 bug.

http://muncyboro.org/

On this page, in IE11, inspect the DIV containing the the header "About Muncy Borough". The containing DIV has the 'col' class assigned to it. I currently have modified the .col class from 
`flex:1`
to
`flex-grow:1`

In in the inspector change it back to `flex:1` and you'll see the columns no longer align properly and overflow into the right sidebar. Setting `flex:1` sets other properties where the defaults aren't the same as other browsers. So you have to be explicit and say that you only want to set `flex-grow` to be set.

**Comment by gmariani** [comment]
Here is what the error originally looked like for the client when I first put this ticket in. This was using the original gridly (unprefixed), although the prefixed doesn't have the -ms- prefix so it's not much different. The screenshots they differ because one was with compatibility mode and the other was without.

![image001](https://cloud.githubusercontent.com/assets/5058619/21225248/fc960db2-c29d-11e6-9337-9696ef1d54cc.png)

![image001-58](https://cloud.githubusercontent.com/assets/5058619/21225250/00e69dbe-c29e-11e6-9eff-60c385a5cb35.png)

**Comment by gmariani** [comment]
Here was the original CSS on the broken site.
`/* Gridly */`
`.row{display:flex}`
`.col{flex:1}`

Here is what I changed it to

`/* Gridly */`
`.row{display: -ms-flexbox;display: -webkit-flex;display:flex;}`
`/*.col{-ms-flex: 1 1 0%;-webkit-flex: 1 1 0%;flex: 1 1 0%}*/`
`.col{-ms-flex-grow:1;-webkit-flex-grow:1;flex-grow:1}`

**Comment by IonicaBizau** [comment]
So, is it just replacing `flex` with `flex-grow`? I guess `autoprefixer` will prefix these.

**Comment by gmariani** [comment]
I'm going to lean towards yes. I was still trying to verify the exact cause so I don't steer you astray. I looked up the original page HTML versus what's live today. I've recreated a simple demo of what the original problem looked like. This works in Chrome and Firefox but fails in IE11.

Looking at this old code I do see I put `flex:0` on a few columns to help control the resizing but that compounded the problem in IE. In the end removing those and switching to `flex-grow` did resolve my issues.
[test.txt](https://github.com/IonicaBizau/gridly/files/654992/test.txt)

**Comment by tunnckoCore** [comment]
Holy Microsoft Gods :laughing:  :laughing:  :laughing:

**Comment by IonicaBizau** [comment]
@gmariani Can you please create a pull request, then? That would help!

**Comment by gmariani** [comment]
I don't use Github, so forgive me in not knowing anything about how github works. I'll create a pull request, but i'll be honest. That is literally what I'm going to do, i'm sorry.

**Comment by gmariani** [comment]
Ok so I see it wants me to merge some branches. I assume you don't want me to do a pull request to merge your two branches... Or are you assuming I made a branch, made changes and then try to merge? I dunno, again sorry.

**Comment by IonicaBizau** [comment]
If I am not wrong we fixed this already...
