### ISSUE TITLE
Gutters

### ISSUE THREAD

**Issue by higoka** [IonicaBizau/gridly#32]
How can i add a 20px gutter to the columns?
Like the bootstrap one

**Comment by mowens86** [comment]
Hi higoka,

I believe this can be achieved when you use a display of grid and grid-column-gap within it.

Here's an example:
https://www.w3schools.com/cssref/tryit.asp?filename=trycss_grid-column-gap

I hope this helps.

**Comment by khamer** [comment]
I assume he's trying to use gridly though - which uses flexbox not grid. I can throw together a PR for gutter support for gridly if that's wanted.

**Comment by higoka** [comment]
> I assume he's trying to use gridly though - which uses flexbox not grid. I can throw together a PR for gutter support for gridly if that's wanted.

that would be awesome!

**Comment by khamer** [comment]
Quick PR above for gutters. If we don't want to merge it, that's fine - I just wanted to show a quick example of what it'd take for the thread at least. Happy Hacktoberfest.
