### ISSUE TITLE
Homepage dead links

### ISSUE THREAD

**Issue by olliephillips** [IonicaBizau/gridly#4]
Noticed the links to the zip downloads on your github.io homepage are dead (at least for me, just now).

Also a question, does Gridly support nesting?

**Comment by IonicaBizau** [comment]
@olliephillips Thanks for heads-up! The branch name was wrong (`master` instead of `gh-pages`). :open_mouth: 

> Also a question, does Gridly support nesting?

Do you mean by putting columns inside of columns inside of columns? If you're asking for that, the answer is _yes_! :smile: 

``` html
<div class="row">
  <div class="col">
    <div class="row">
      <div class="col">1 / 4</div>
      <div class="col">1 / 4</div>
    </div>
  </div>
  <div class="col">1 / 2</div>
</div>
```
