### ISSUE TITLE
Demo page has a flexbox height bug in Safari 9.x (OS X, iOS)

### ISSUE THREAD

**Issue by opattison** [IonicaBizau/gridly#6]
![2015-12-11 flex-basis bug in Safari – collapsed vertical height](https://cloud.githubusercontent.com/assets/885300/11753309/676081d6-a012-11e5-8ae5-07ccc3437de4.png)

Spotted in Safari OS X 9.0.1 on OS X. On narrower views (below 48em, I believe), the grid collapses vertically, creating a visual bug. This is caused by how Safari handles `flex: 0 0 100%`. Setting this to `flex: 0 0 auto` should fix this behavior, but more cross-browser testing is needed since Chrome, Firefox and others may treat this differently (although I believe my fix should work, so do test it out). `flex-basis: 100%` is the issue here. Note that `100%` works for horizontal (`row`) but fails for vertical (`column`) flex layouts in Safari. `auto` (the default value for `flex-basis`) negates the issue for either `flex-direction`.

I have run into this issue on multiple other sites. I've looked at the spec and I'm not yet entirely sure whether Safari has it right or wrong.

Let me know if you want more testing or a PR.

**Comment by IonicaBizau** [comment]
That's a nice catch, @opattison! :sparkles: 
Yes, test it on other browsers and if it works, would be happy to accept a pull request regarding this fix! :smile: 

It's funny that `100%` and `auto` have same length, so, the size will not be modified. :grin:

**Comment by opattison** [comment]
I believe this is [a currently unresolved flex bug in Safari](https://github.com/philipwalton/flexbugs#1-minimum-content-sizing-of-flex-items-not-honored). I have a really brief fix that will address the issue – making a PR now. I hope this solution will work. I think it is necessary to support iOS and OS X Safari users, which is a pretty big target.

**Comment by opattison** [comment]
IE 11 failed with this flex bug in exactly the same way – my fix in #8 addresses both equally.

**Comment by IonicaBizau** [comment]
Fixed in `1.2.0`, thanks to you! :+1: :clap:

**Comment by tavax** [comment]
Allways not working on Safari OSX
