### ISSUE TITLE
Docs: Browser Support

### ISSUE THREAD

**Issue by cthedot** [IonicaBizau/gridly#7]
would be nice to have a litte more info about which browsers are supported, e.g. which of the old flexbox syntaxes are in and which are not? Thanks!

**Comment by cthedot** [comment]
oh, guess should have checked first. Only newest syntax... Guess a note that autoprefixer to add support for older browsers incl. e.g. Safari, IE etc would be almost a requirement?

**Comment by IonicaBizau** [comment]
That's very good idea, @cthedot! :+1: 
Would be nice to have a note regarding which browsers are supported. :memo: 

> Guess a note that autoprefixer to add support for older browsers incl. e.g. Safari, IE etc would be almost a requirement?

What do you mean by that? Not sure what _autoprefixer_ is...

**Comment by cthedot** [comment]
https://github.com/postcss/autoprefixer to add support for browsers which do still use a prefixed (-webkit-) or older version of the flexbox spec(s). Maybe you knew that anyway and my comment was just all too brief.

If I'd use gridly without using autoprefixer it would not work on e.g. IE10, Safari 8 (and iOS 8) etc. http://caniuse.com/#search=flexbox

Guess at least for most projects may ignore browsers without any flexbox support (IE8/9 etc) but think would be good to at least support the others. One way would be to add a release with all prefixes/versions in it OR at least add note about the need to use something like autoprefixer in any project (other tools work too of course).

**Comment by IonicaBizau** [comment]
@cthedot Oh, I see! Good points! :100: 

I think a release containing the prefixed `flexbox` things would be handy, but it should obviously generated by the `release` script.

Also, the docs should be updated then.

Would you like to do that? :grin:

**Comment by cthedot** [comment]
hehe...
But seriously, I might do it but I know by my free time it won't happen before end of this year and guess it should be before that. Maybe best to update the docs as a first stop first?
